comment=""

[train]

# model_path = "nips_splinenet_{}_{}_{}_bt_{}_lr_{}_trsz_{}_tsz_{}_wght_{}"

# GT point cloud path
# gt_pc = "../Ducky/duck1.obj"
gt_pc = "/home/lizeth/Documents/meshes/duck_dynamic"
# gt_pc = "../../meshes/sampled/sphere"
# gt_pc = "../../meshes/duck_pc_possion"

# path to the pre-trained model
# pretrain_model_path = ""

# Whether to input the normals or not
normals = False

# number of sampled points
num_points = 1

loss_weight = 0.9

batch_size = 36

num_epochs = 3000
axis = z

# number of control points used on u, v
ctrpts_size = 25
ctrlpts_size_u = 12
ctrlpts_size_v = 12

# base function degree
degree = 3

# resolution on u, v
resolution_u = 31
resolution_v = 30
sample_size_u = 31
sample_size_v = 30
# reconstruct surface on prediction
out_dim_u = 60
out_dim_v = 60
# optimzer
optim = adam

accum = 4

# Learning rate
lr1 = 0.1
lr2 = 0.001
# Whether to schedule the learning rate or not
lr_sch = True

# Number of epochs to wait before decaying the learning rate.
patience = 8

mode = 0

# chamfer | mse
loss_type = chamfer

ignore_uv = True

